### PR TITLE
Implement equals method for JsonAdaptedStudent to fix getAttendance

### LINKED ISSUE #198: Attendance read from JSON always returns false
This is likely caused by there being no equals method implemented for `JsonAdaptedStudent`, so it defaults to using object equality, which returns false due to two different instances being compared.

### PR DESCRIPTION
**Pull request by notnotmax**
Closes #198.

### CODE REVIEW

File: src/main/java/seedu/address/storage/JsonAdaptedLesson.java [hunk 1]
```diff
@@ -151,8 +151,10 @@ public Lesson toModelType(AddressBook addressBook) throws IllegalValueException
      * @param jsonStudent JsonAdaptedStudent representing the student to search for.
      * @return Boolean representing the student's attendance for this lesson, or false if no entry is found.
      */
-    private boolean getAttendance(JsonAdaptedStudent jsonStudent) {
+    protected boolean getAttendance(JsonAdaptedStudent jsonStudent) {
         for (Pair<JsonAdaptedStudent, Boolean> pair : attendanceList) {
+            // A (faster) alternative is to only check using the student's name, but issues could arise if there
+            // happen to be multiple students with the same name in the JSON file.
```
Comment (S-K-Y-Light) [inline src/main/java/seedu/address/storage/JsonAdaptedLesson.java:157]: Indeed. A good way of ensuring Defensive Programming by checking Student Details instead.

File: src/main/java/seedu/address/storage/Pair.java [hunk 2]
```diff
@@ -14,6 +14,15 @@ public class Pair <K, V> implements Serializable {
     private final K key;
     private final V value;
 
+    /**
+     * Fulfils the role of a dummy constructor for JSON file reading compatibility.
+     * I don't know why this is needed. DO NOT USE IN CODE.
+     */
+    public Pair() {
```
Comment (S-K-Y-Light) [inline src/main/java/seedu/address/storage/Pair.java:21]: Similar to my other comment in PR #195. Would it better to use private accessor here? We wouldn't want to use this dummy constructor.

**Review by S-K-Y-Light — COMMENTED** [review]
LGTM. Just Small Nits

File: src/main/java/seedu/address/storage/Pair.java (hunk 2 above)
Comment (S-K-Y-Light) [reply src/main/java/seedu/address/storage/Pair.java:21]: Pair Class will not be necessary in the subsequent PRs. Will be removing Pair.java. So closing this as resolved.
