### PR TITLE
Fix Consultation GUI not updating and prevent adding duplicate students

### LINKED ISSUE #141: cannot add duplicate student to consult

### LINKED ISSUE #143: update GUI for addtoconsult
1. addtoconsultcommand -> update model
2. removefromconsult -> update model
3. modelmanager add for removefromconsult

### PR DESCRIPTION
**Pull request by notnotmax**
Closes #143. Closes #141.

Currently, the consultation list GUI does not update after performing `addtoconsult` and `removefromconsult`, hence any changes to the students in a consultation is not reflected on screen. Additionally, it is currently possible to add the same student to a consult multiple times.

Let's:
- implement the method `setConsult` in `Model` which replaces the old `Consultation` instance with a new one, thus updating the `ObservableList` so the GUI is able to observe the change, rather than modify the `Consultation` instance directly.
- implement a check to prevent a duplicate `Student` from being added to a `Consultation`.

### CODE REVIEW

File: src/main/java/seedu/address/model/consultation/Consultation.java [hunk 1]
```diff
@@ -34,6 +37,20 @@ public Consultation(Date date, Time time, List<Student> students) {
...
 
+    /**
+     * Constructs a copy of the given consultation.
+     * Creates new instances of date, time and the student list (not the students) to
+     * reduce the risk of accidental mutation.
+     *
+     * @param consultation The consultation to copy.
+     */
+    public Consultation(Consultation consultation) {
+        requireNonNull(consultation);
```
Comment (S-K-Y-Light) [inline src/main/java/seedu/address/model/consultation/Consultation.java:48]: Nice Use of Assertions

File: src/main/java/seedu/address/logic/commands/consultation/RemoveFromConsultCommand.java
Comment (S-K-Y-Light) [inline src/main/java/seedu/address/logic/commands/consultation/RemoveFromConsultCommand.java:1]: Any Reason for the change from "consultationToEdit" to "editedConsultation"? Either way works.

File: src/main/java/seedu/address/logic/commands/consultation/AddToConsultCommand.java
Comment (S-K-Y-Light) [inline src/main/java/seedu/address/logic/commands/consultation/AddToConsultCommand.java:1]: Any Reason for the change from "consultationToEdit" to "editedConsultation"? Either way works.

File: src/main/java/seedu/address/model/AddressBook.java [hunk 2]
```diff
@@ -126,6 +128,21 @@ public void setStudent(Student target, Student editedStudent) {
         students.setStudent(target, editedStudent);
     }
 
+    /**
+     * Replaces the given consultation {@code target} in the list with {@code editedConsult}.
+     * {@code target} must exist in TAHub.
+     */
+    public void setConsult(Consultation target, Consultation editedConsult) {
+        requireAllNonNull(target, editedConsult);
```
Comment (S-K-Y-Light) [inline src/main/java/seedu/address/model/AddressBook.java:136]: Nice Use of Assertions

**Review by S-K-Y-Light — APPROVED** [review]
LGTM
