### PR TITLE
Change NameContainsKeywordsPredicate logic

### LINKED ISSUE #101: Fix find not working with spaces in name
Currently, `find n/Alice Benson` does not work, and throws an InvocationTargetException.
However, names with spacing works in the add command, likely indicating an issue exclusive to the parsing of the find command.

### PR DESCRIPTION
**Pull request by notnotmax**
Closes #101.

Previously, `NameContainsKeywordsPredicate` makes use of `StringUtil.containsWordIgnoreCase`, which only accepts a single word as an argument.

Let's,
- Change the logic to accept a string literal as is, e.g. `find n/alice tan` will successfully find a student containing the string sequence "alice tan", case-insensitive.

### CODE REVIEW

**Review by yhanyi — APPROVED** [review]
LGTM, thanks a lot for debugging

File: src/main/java/seedu/address/model/student/NameContainsKeywordsPredicate.java [hunk 1]
```diff
@@ -18,8 +17,9 @@ public NameContainsKeywordsPredicate(List<String> keywords) {
 
     @Override
     public boolean test(Student student) {
+        String lowercaseName = student.getName().fullName.toLowerCase();
         return keywords.stream()
-                .anyMatch(keyword -> StringUtil.containsWordIgnoreCase(student.getName().fullName, keyword));
+                .anyMatch(keyword -> lowercaseName.contains(keyword.toLowerCase()));
```
Comment (S-K-Y-Light) [inline src/main/java/seedu/address/model/student/NameContainsKeywordsPredicate.java:22]: Great that you've created "lowercaseName" as a variable. This helps to improve the readability of the code.

File: src/test/java/seedu/address/logic/parser/FindCommandParserTest.java [hunk 2]
```diff
@@ -38,7 +37,20 @@ public void parse_validSingleNameArg_returnsFindCommand() throws ParseException
...
+    public void parse_validSpacedNameArg_returnsFindCommand() {
+        FindCommand expectedFindCommand = new FindCommand(
+                new NameContainsKeywordsPredicate(List.of("Alice Tan"))
+        );
+
+        // no leading and trailing whitespaces
+        assertParseSuccess(parser, " n/Alice Tan", expectedFindCommand);
+
+        // multiple whitespaces around keyword
+        assertParseSuccess(parser, " \n n/Alice Tan\n  \t", expectedFindCommand);
```
Comment (S-K-Y-Light) [inline src/test/java/seedu/address/logic/parser/FindCommandParserTest.java:49]: I don't think that User is able to input indentations or new line in the name, so the inclusion of "\n" as a testcase isn't entirely necessary? But it's nice that you've considered such cases.

**Review by S-K-Y-Light — COMMENTED** [review]
LGTM. Great that the code is simple to understand.
