### PR TITLE
Fix Command Type 

### LINKED ISSUE #121: Commands throw NullPointerException in console even when working
Using nearly any command results in the following popup.
image
This is likely caused by this constructor setting the default value of commandType (and tabIndex) to null.
image
Maybe it would be in the interest of code quality to remove this constructor and opt for `commandType` as a required argument in `CommandResult`?

### PR DESCRIPTION
**Pull request by S-K-Y-Light**
See Issue #121 for more details.

### CODE REVIEW

File: src/main/java/seedu/address/logic/commands/AddCommand.java [hunk 1]
```diff
@@ -62,7 +63,7 @@ public CommandResult execute(Model model) throws CommandException {
         }
 
         model.addStudent(toAdd);
-        return new CommandResult(String.format(MESSAGE_SUCCESS, Messages.format(toAdd)));
+        return new CommandResult(String.format(MESSAGE_SUCCESS, Messages.format(toAdd)), CommandType.ADDSTUDENT);
```
Comment (notnotmax) [inline src/main/java/seedu/address/logic/commands/AddCommand.java]: It may be easier to reuse COMMAND_TYPE here rather than explicit usage of CommandType.ADDSTUDENT. Same for the other command classes.

**Review by notnotmax — COMMENTED** [review]
May consider some minor changes, other than that lgtm

File: src/main/java/seedu/address/logic/commands/AddCommand.java (hunk 1 above)
Comment (S-K-Y-Light) [reply src/main/java/seedu/address/logic/commands/AddCommand.java]: Good Catch. Changed Accordingly.

**Comment by marcusjhang** [comment]
lgtm
